### ISSUE TITLE
highway=turning_circle is a valid end point

### ISSUE THREAD

**Issue by matkoniecz** [geofabrik/osmi_routing#13]
https://www.openstreetmap.org/node/2481670708

https://resultmaps.neis-one.org/hdyc-osmi-issues?uid=1722488 spuriously reports 

<html><body>

113. | NODE | 2481670708 | routing | unconnected_open_ends_2 (?) | 2022-01-10 03:36:55.674 | 34012389

</body>
</html>

**Comment by Nakaner** [comment]
`highway=turning_circle` might be a valid end point if one views the world in car-centric way. However, for pedestrians such dead-end street often have a footpath which connects to another street. In your example, it looks to me that a `highway=footway` should connect the existing footway and the street in order to avoid pedestrian routing starting on the street (at a location north on the northern side of the street) run around the block because the footway is mapped separately. Only if there is no connection between the footway and the street, such mapping is right.

OSMI Routing points out a potential tagging issue here and that's why I will not fix this issue.
